# DO NOT EDIT THIS FILE

from MyFifteenPuzzle import *
from MySearch import *

from sys import argv,exit

def usage():
	print 'You must enter a valid tuple of tuples for a game state inside quotes.'
	print 'Try running without parameters to see an example.'
	exit()

initial = None
if len(argv) > 1:
	try:
		initial = eval(eval("".join(argv[1:])))
	except:
		usage
		
	if type(initial) != type(tuple()):
		usage()
	if len(initial) != 4:
		usage()
	contents = []
	for i in range(4):
		if type(initial[i]) != type(tuple()):
			usage()
		if len(initial[i]) != 4:
			usage()
		contents.extend(list(initial[i]))
	contents.sort()
	if contents != range(16):
		usage()
		
problem = MyFifteenPuzzle(initial)
state = problem.getInitial()

print 'Initial state:', state
print

problem.initializeDraw()
problem.draw(state)

search = MySearch()
solution = search.perform(problem)

print 'Solution of length', len(solution), 'found.'

for a in solution:
	problem.drawAction(state,a)
	state = problem.result(state,a)

if state != problem.getGoal():
	print 'Solution state not reached'
else:
	print 'Correct solution found'
